rename_pairs = {
    "Small C5-L Emergency Shield Overload I": "Small C5-L Compact Shield Booster",
    "Small Clarity Ward Booster I": "Small Clarity Ward Enduring Shield Booster",
    "Medium C5-L Emergency Shield Overload I": "Medium C5-L Compact Shield Booster",
    "Medium Clarity Ward Booster I": "Medium Clarity Ward Enduring Shield Booster",
    "Large C5-L Emergency Shield Overload I": "Large C5-L Compact Shield Booster",
    "Large Clarity Ward Booster I": "Large Clarity Ward Enduring Shield Booster",
    "X-Large C5-L Emergency Shield Overload I": "X-Large C5-L Compact Shield Booster",
    "X-Large Clarity Ward Booster I": "X-Large Clarity Ward Enduring Shield Booster",
    "Small Converse Deflection Catalyzer": "Small Clarity Ward Enduring Shield Booster",
    "Small Neutron Saturation Injector I": "Small C5-L Compact Shield Booster",
    "Medium Converse Deflection Catalyzer": "Medium Clarity Ward Enduring Shield Booster",
    "Medium Neutron Saturation Injector I": "Medium C5-L Compact Shield Booster",
    "Large Converse Deflection Catalyzer": "Large Clarity Ward Enduring Shield Booster",
    "Large Neutron Saturation Injector I": "Large C5-L Compact Shield Booster",
    "X-Large Converse Deflection Catalyzer": "X-Large Clarity Ward Enduring Shield Booster",
    "X-Large Neutron Saturation Injector I": "X-Large C5-L Compact Shield Booster",
    "Small Asymmetric Remote Capacitor Transmitter": "Small Radiative Scoped Remote Capacitor Transmitter",
    "Small 'Regard' Remote Capacitor Transmitter": "Small Inductive Compact Remote Capacitor Transmitter",
    "Medium Asymmetric Remote Capacitor Transmitter": "Medium Radiative Scoped Remote Capacitor Transmitter",
    "Medium 'Regard' Remote Capacitor Transmitter": "Medium Inductive Compact Remote Capacitor Transmitter",
    "Large Asymmetric Remote Capacitor Transmitter": "Large Radiative Scoped Remote Capacitor Transmitter",
    "Large 'Regard' Remote Capacitor Transmitter": "Large Inductive Compact Remote Capacitor Transmitter",
    "Small Partial E95a Remote Capacitor Transmitter": "Small Radiative Scoped Remote Capacitor Transmitter",
    "Small Murky Remote Capacitor Transmitter": "Small Inductive Compact Remote Capacitor Transmitter",
    "Medium Partial E95b Remote Capacitor Transmitter": "Medium Radiative Scoped Remote Capacitor Transmitter",
    "Medium Murky Remote Capacitor Transmitter": "Medium Inductive Compact Remote Capacitor Transmitter",
    "Large Partial E95c Remote Capacitor Transmitter": "Large Radiative Scoped Remote Capacitor Transmitter",
    "Large Murky Remote Capacitor Transmitter": "Large Inductive Compact Remote Capacitor Transmitter",
    "Micro Electrochemical Capacitor Booster I": "'Seed' Micro Capacitor Booster I",
    "Small Electrochemical Capacitor Booster I": "Small F-RX Compact Capacitor Booster",
    "Medium Electrochemical Capacitor Booster I": "Medium F-RX Compact Capacitor Booster",
    "Heavy Electrochemical Capacitor Booster I": "Heavy F-RX Compact Capacitor Booster",
    "Micro Brief Capacitor Overcharge I": "'Seed' Micro Capacitor Booster I",
    "Micro Tapered Capacitor Infusion I": "'Seed' Micro Capacitor Booster I",
    "Micro F-RX Prototype Capacitor Boost": "'Seed' Micro Capacitor Booster I",
    "Micro Capacitor Booster I": "'Seed' Micro Capacitor Booster I",
    "Micro Capacitor Booster II": "'Seed' Micro Capacitor Booster I",
    "Ammatar Navy Micro Capacitor Booster": "'Seed' Micro Capacitor Booster I",
    "Dark Blood Micro Capacitor Booster": "'Seed' Micro Capacitor Booster I",
    "True Sansha Micro Capacitor Booster": "'Seed' Micro Capacitor Booster I",
    "Imperial Navy Micro Capacitor Booster": "'Seed' Micro Capacitor Booster I",
    "Small Brief Capacitor Overcharge I": "Small F-RX Compact Capacitor Booster",
    "Small Tapered Capacitor Infusion I": "Small F-RX Compact Capacitor Booster",
    "Small F-RX Prototype Capacitor Boost": "Small F-RX Compact Capacitor Booster",
    "Medium Brief Capacitor Overcharge I": "Medium F-RX Compact Capacitor Booster",
    "Medium Tapered Capacitor Infusion I": "Medium F-RX Compact Capacitor Booster",
    "Medium F-RX Prototype Capacitor Boost": "Medium F-RX Compact Capacitor Booster",
    "Heavy Brief Capacitor Overcharge I": "Heavy F-RX Compact Capacitor Booster",
    "Heavy Tapered Capacitor Infusion I": "Heavy F-RX Compact Capacitor Booster",
    "Heavy F-RX Prototype Capacitor Boost": "Heavy F-RX Compact Capacitor Booster",
    "Adaptive Invulnerability Field": "Multispectrum Shield Hardener",
    "EM Ward Field": "Anti-EM Shield Hardener",
    "Explosive Deflection Field": "Anti-Explosive Shield Hardener",
    "Kinetic Deflection Field": "Anti-Kinetic Shield Hardener",
    "Thermal Dissipation Field": "Anti-Thermal Shield Hardener",
    "Limited Adaptive Invulnerability Field I": "Compact Multispectrum Shield Hardener",
    "Limited 'Anointed' EM Ward Field": "Compact Anti-EM Shield Hardener",
    "Limited Explosive Deflection Field I": "Compact Anti-Explosive Shield Hardener",
    "Limited Kinetic Deflection Field I": "Compact Anti-Kinetic Shield Hardener",
    "Limited Thermal Dissipation Field I": "Compact Anti-Thermal Shield Hardener",
    "Adaptive Invulnerability Shield Hardener": "Multispectrum Shield Hardener",
    "Anti-EM Screen Reinforcer": "EM Shield Reinforcer",
    "Anti-Explosive Screen Reinforcer": "Explosive Shield Reinforcer",
    "Anti-Kinetic Screen Reinforcer": "Kinetic Shield Reinforcer",
    "Anti-Thermal Screen Reinforcer": "Thermal Shield Reinforcer",
    "Anti-EM Pump": "EM Armor Reinforcer",
    "Anti-Explosive Pump": "Explosive Armor Reinforcer",
    "Anti-Kinetic Pump": "Kinetic Armor Reinforcer",
    "Anti-Thermal Pump": "Thermal Armor Reinforcer",
    "Armor EM Hardener I": "EM Armor Hardener I",
    "Corpus C-Type Armor Kinetic Hardener": "Corpus C-Type Kinetic Armor Hardener",
    "Experimental modules were": "Experimental Enduring modules",
    "Prototype modules were": "Prototype Compact modules",
    "Upgraded EM Armor Hardener I": "Experimental Enduring EM Armor Hardener I",
    "Upgraded Explosive Armor Hardener I": "Experimental Enduring Explosive Armor Hardener I",
    "Upgraded Kinetic Armor Hardener I": "Experimental Enduring Kinetic Armor Hardener I",
    "Upgraded Thermal Armor Hardener I": "Experimental Enduring Thermal Armor Hardener I",
    "Limited EM Armor Hardener I": "Prototype Compact EM Armor Hardener I",
    "Limited Explosive Armor Hardener I": "Prototype Compact Explosive Armor Hardener I",
    "Limited Kinetic Armor Hardener I": "Prototype Compact Kinetic Armor Hardener I",
    "Limited Thermal Armor Hardener I": "Prototype Compact Thermal Armor Hardener I",
    "Dark Blood Tracking Disruptor": "'Investor' Tracking Disruptor I",
    "EM Resistance Amplifiers": "EM Shield Amplifiers",
    "Explosive Resistance Amplifiers": "Explosive Shield Amplifiers",
    "Kinetic Resistance Amplifiers": "Kinetic Shield Amplifiers",
    "Thermal Resistance Amplifiers": "Thermal Shield Amplifiers",
    "EM Ward Amplifier": "EM Shield Amplifier",
    "Explosive Deflection Amplifier": "Explosive Shield Amplifier",
    "Kinetic Deflection Amplifier": "Kinetic Shield Amplifier",
    "Thermal Dissipation Amplifier": "Thermal Shield Amplifier",
    "Basic EM Ward Amplifier": "'Basic' EM Shield Amplifier",
    "Basic Explosive Deflection Amplifier": "'Basic' Explosive Shield Amplifier",
    "Basic Kinetic Deflection Amplifier": "'Basic' Kinetic Shield Amplifier",
    "Basic Thermal Dissipation Amplifier": "'Basic' Thermal Shield Amplifier",
    "Supplemental EM Ward Amplifier": "'Basic' EM Shield Amplifier",
    "Supplemental Explosive Deflection Amplifier": "'Basic' Explosive Shield Amplifier",
    "Supplemental Kinetic Deflection Amplifier": "'Basic' Kinetic Shield Amplifier",
    "Supplemental Thermal Dissipation Amplifier": "'Basic' Thermal Shield Amplifier",
    "Upgraded EM Ward Amplifier I": "Compact EM Shield Amplifier",
    "Upgraded Explosive Deflection Amplifier I": "Compact Explosive Shield Amplifier",
    "Upgraded Kinetic Deflection Amplifier I": "Compact Kinetic Shield Amplifier",
    "Upgraded Thermal Dissipation Amplifier I": "Compact Thermal Shield Amplifier",
    "Adaptive Resistance Plating": "Multispectrum Coatings",
    "EM Resistance Plating": "EM Coatings",
    "Explosive Resistance Plating": "Explosive Coatings",
    "Kinetic Resistance Plating": "Kinetic Coatings",
    "Thermal Resistance Plating": "Thermal Coatings",
    "Adaptive Nano Plating I": "Multispectrum Coating I",
    "EM Plating I": "EM Coating I",
    "Explosive Plating I": "Explosive Coating I",
    "Kinetic Plating I": "Kinetic Coating I",
    "Thermal Plating I": "Thermal Coating I",
    "Limited Layered Plating I": "Upgraded Layered Coating I",
    "'Scarab' Layered Plating I": "Upgraded Layered Coating I",
    "'Grail' Layered Plating I": "Upgraded Layered Coating I",
    "Limited Adaptive Nano Plating I": "Upgraded Multispectrum Coating I",
    "'Collateral' Adaptive Nano Plating I": "Upgraded Multispectrum Coating I",
    "'Refuge' Adaptive Nano Plating I": "Upgraded Multispectrum Coating I",
    "Limited EM Plating I": "Upgraded EM Coating I",
    "'Contour' EM Plating I": "Upgraded EM Coating I",
    "'Spiegel' EM Plating I": "Upgraded EM Coating I",
    "Limited Explosive Plating I": "Upgraded Explosive Coating I",
    "Experimental Explosive Plating I": "Upgraded Explosive Coating I",
    "'Aegis' Explosive Plating I": "Upgraded Explosive Coating I",
    "Limited Kinetic Plating I": "Upgraded Kinetic Coating I",
    "Experimental Kinetic Plating I": "Upgraded Kinetic Coating I",
    "'Element' Kinetic Plating I": "Upgraded Kinetic Coating I",
    "Limited Thermal Plating I": "Upgraded Thermal Coating I",
    "Experimental Thermal Plating I": "Upgraded Thermal Coating I",
    "Prototype Thermal Plating I": "Upgraded Thermal Coating I",
}

renameables = ["Adaptive Invulnerability Shield Hardener"]
